on:
  workflow_dispatch:
  

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Merge upstream
        run: |
          git config --global user.name 'autoz'
          git config --global user.email '213220254@qq.com'
          git pull -r --unshallow
          git remote add upstream http://git.zjnsans.top/Autoz/AutozShell.git
          git fetch upstream
          git checkout main
          git merge -r --no-edit upstream/main
          git push origin main
          git fetch upstream --tags
          git push --tags
